config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do
    resources :comments, only: %i[index create destroy]
  end
  resources :users, only: :show do
    collection do
      get 'my_post'
      get 'need_login'
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  acts_as_taggable

  validates :title, presence: true
  validates :body, presence: true
  validates :is_publish, inclusion: { in: [true, false] }

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validates :email, uniqueness: true
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_post, only: %i[create]

  def create
    if @post.comments.create(comment_params)
      redirect_to post_path(@post)
    else
      @comments = @post.connects.includes(:user)
      render "posts/#{@post}"
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    if comment.destroy
      redirect_to post_path(comment.post)
    else
      render "/posts/#{comment.post}"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(user_id: current_user.id, post_id: params[:post_id])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :move_to_session, only: %i[new edit]
  before_action :set_post, only: %i[show edit update destroy]
  before_action :set_publish_posts, only: %i[index show]

  def index; end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    redirect_to root_path unless current_user.id == @post.user_id
  end

  def update
    if @post.update(post_params)
      redirect_to my_post_users_path
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to my_post_users_path
    else
      render :my_post
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :is_publish, :tag_list).merge(user_id: current_user.id)
  end

  def move_to_session
    redirect_to need_login_users_path unless user_signed_in?
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def set_publish_posts
    @posts = Post.includes(:user).where(is_publish: true).order('created_at DESC').page(params[:page]).per(24)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :move_to_session, only: [:my_post]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.where(is_publish: true).order('created_at DESC').page(params[:page]).per(30)
  end

  def my_post
    @posts = current_user.posts.order('created_at DESC').page(params[:page]).per(30)
  end

  def need_login; end

  private

  def move_to_session
    redirect_to need_login_users_path unless user_signed_in?
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContentShare</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_tag_list.html.erb
<div class="post_tag_list">
  <% tag_list.each do |tag| %>
    <span><%= tag %></span>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/header' %>

<div class="new_post">
  <%= form_with model: @post, class: "new_post_form", local: true do |f| %>
    <%= f.text_field :title, class: "new_post_title", placeholder: "タイトル", maxlength:"200" %>
    <%= f.text_area :body, class: "new_post_body" %>
    <div class="new_tag_wrap">
      <%= f.label :tag_list, "タグ", class:"post_tag_label" %>
      <%= f.text_field :tag_list, value: @post.tag_list.join(','), class:"new_post_tag", placeholder: "カンマで区切る" %>
    </div>
    <div class="publish_check_wrap">
      <%= f.label :is_publish , "公開", class: "is_publish_label" %>
      <%= f.check_box :is_publish, checked_value: true, unchecked_value: false, class: "publish_check_box" %>
    </div>
    <%= f.submit "更新", class: "new_post_submit" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="wrapper">
  <%= render "shared/header" %>
  <%= render "shared/side_bar" %>
  <%= render "shared/main_post" %>
</div>

app/views/posts/new.html.erb
<%= render 'shared/header' %>

<div class="new_post">
  <%= form_with model: @post, class: "new_post_form", local: true do |f| %>
    <%= f.text_field :title, class: "new_post_title", placeholder: "タイトル", maxlength:"200", required: true %>
    <%= f.text_area :body, class: "new_post_body", required: true %>
    <div class="new_tag_wrap">
      <%= f.label :tag_list, "タグ", class:"post_tag_label" %>
      <%= f.text_field :tag_list, value: @post.tag_list.join(','), class:"new_post_tag", placeholder: "カンマで区切る" %>
    </div>
    <div class="publish_check_wrap">
      <%= f.label :is_publish , "公開", class: "is_publish_label" %>
      <%= f.check_box :is_publish, checked: false, checked_value: true, unchecked_value: false, class: "publish_check_box" %>
    </div>
    <%= f.submit "投稿", class: "new_post_submit" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="wrapper">
  <%= render 'shared/header' %>
  <%= render "shared/side_bar" %>
  <main class="main_post">
    <div class="post_show_wrap">
      <div class="post_show_box">
        <ul class="post_show">
          <li class="post_user_show"><%= @post.user.nickname %></li>
          <li class="post_title_show"><%= @post.title %></li>
          <li class="post_body_show"><%= @post.body %></li>
          <li><%= render partial: "tag_list", locals: { tag_list: @post.tag_list } %></li>
        </ul>
        <div class="comment_view_wrap">
          <%# コメント投稿フォーム %>
          <% if user_signed_in? %>
            <%= form_with model: [@post, @comment], class:"comment_form" , local: true do |f| %>
              <%= f.text_area :body, class:"comment_area", required: true %>
              <%= f.submit "コメント", class:"comment_submit" %>
            <% end %>
          <% end %>

          <%# コメント一覧表示 %>
          <div class="comment_lists">
            <% @post.comments.each_with_index do |comment, i| %>
              <div class="comment_wrap">
                <li class="comment_user_name"><%= "#{i+1}. #{comment.user.nickname} :" %></li>
                <li class="comment"><%= "#{comment.body}" %></li>
                <% if user_signed_in? && current_user.id == comment.user_id %>
                  <li><%= link_to "削除", post_comment_path(comment.post, comment.id), method: :delete, class:"comment_delete" %></li>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="main_post_wrap">
        <div class="post_lists">
          <% @posts.each do |post| %>
            <% if post.is_publish %>
              <ul class="post">
                <%= link_to user_path(post.user), class:'post_user_link' do %>
                  <li class="post_user_name"><%= post.user.nickname %></li>
                <% end %>
                <%= link_to post_path(post), class: 'post_show_link' do %>
                  <li class="post_title"><%= post.title %></li>
                  <li class="post_body"><%= post.body %></li>
                <% end %>
              </ul>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </main>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <ul class="error_alert">
    <% model.errors.full_messages.each do |message| %>
      <li class="error_message"><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_header.html.erb
<header class="post_header">
  <nav class="header_nav">
    <%= image_tag 'hamburger-menu.svg', class: "hamburger_menu" %>
    <%= link_to "Share", root_path, class: "home_title" %>
    <ul class="user_status_nav">
      <% if user_signed_in? %>
        <li class="user_status user_name"><%= current_user.nickname %></li>
        <li class="user_status logout"><%= link_to 'ログアウト', destroy_user_session_path,  method: :delete %></li>
      <% else %>
        <li class="user_status sign_up"><%= link_to '新規登録', new_user_registration_path %></li>
        <li class="user_status login"><%= link_to 'ログイン', new_user_session_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/shared/_main_post.html.erb
<main class="main_post">
  <div class="main_post_wrap">
    <div class="post_lists">
      <%= render partial: "shared/post_index", locals: { resources: @posts } %>
    </div>
      <%= link_to_prev_page @posts, "前へ" %>
      <%= link_to_next_page @posts, '次へ' %>
  </div>
</main>

app/views/shared/_post_index.html.erb
<% resources.each do |post| %>
  <ul class="post">
    <%= link_to user_path(post.user), class:'post_user_link' do %>
      <li class="post_user_name"><%= post.user.nickname %></li>
    <% end %>
    <%= link_to post_path(post), class: 'post_show_link' do %>
      <li class="post_title"><%= post.title %></li>
      <li class="post_body"><%= post.body %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_side_bar.html.erb
<aside class="side_bar">
  <div class="side_bar_wrap">
    <%= link_to '投稿する', new_post_path, class: "new_post_btn" %>

    <div class="side_menu_lists">
      <%= link_to "ホーム", root_path, class: "all_post_page" %>
      <%= link_to "投稿", my_post_users_path, class: "my_post_page" %>
    <div>
  </div>
</aside>

app/views/users/my_post.html.erb
<div class="wrapper">
  <%= render 'shared/header' %>
  <%= render "shared/side_bar" %>
  <main class="main_post">
    <p class="my_post_text">あなたの投稿</p>
    <div class="main_post_wrap">
      <div class="post_lists">
        <% @posts.each do |post| %>
          <ul class="post">
            <%= link_to user_path(post.user), class:'post_user_link' do %>
              <li class="post_user_name"><%= post.user.nickname %></li>
            <% end %>
            <%= link_to post_path(post), class: 'post_show_link' do %>
              <li class="post_title"><%= post.title %></li>
              <li class="post_body"><%= post.body %></li>
            <% end %>
            <div class="my_post_nav">
              <li><%= link_to '編集', edit_post_path(post), class:"post_edit_link" %></li>
              <li><%= link_to '詳細', post_path(post), class:"post_show_link" %></li>
              <li><%= link_to '削除', post_path(post), method: :delete, class:"post_delete_link" %>
              <% if post.is_publish %>
                <span class="publish_status_str">公開</span>
              <% else %>
                <span class="publish_status_str">非公開</span>
              <% end %>
            </div>
          </ul>
        <% end %>
      </div>
    </div>
      <%= link_to_prev_page @posts, "前へ" %>
      <%= link_to_next_page @posts, '次へ' %>
  </main>
</div>

app/views/users/need_login.html.erb
<%= render "shared/header" %>

<div class="need_login_wrap">
  <p class="need_login_text">ログインが必要です</p>
  <%= link_to '新規投稿', new_user_registration_path, class: "need_sign_up" %>
  <%= link_to 'ログイン', new_user_session_path, class: "need_login" %>
</div>

app/views/users/show.html.erb
<div class="wrapper">
  <%= render 'shared/header' %>
  <%= render "shared/side_bar" %>
  <main class="main_post">
    <p class="user_profile_text"><%= "#{@user.nickname}さんの投稿" %></p>
    <div class="main_post_wrap">
      <div class="post_lists">
        <% @posts.each do |post| %>
          <% if post.is_publish %>
            <ul class="post">
              <%= link_to user_path(post.user), class:'post_user_link' do %>
                <li class="post_user_name"><%= post.user.nickname %></li>
              <% end %>
              <%= link_to post_path(post), class: 'post_show_link' do %>
                <li class="post_title"><%= post.title %></li>
                <li class="post_body"><%= post.body %></li>
              <% end %>
            </ul>
          <% end %>
        <% end %>
      </div>
    </div>
  </main>
<div>